version: '2'
services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PRIMARY_USER: postgres
      POSTGRES_PRIMARY_PASSWORD: yoursecurepassword
      POSTGRES_DB: ${POSTGRES_DB:-db-template}
      TZ: GMT
    ports:
      - 15432:5432
    volumes:
      - ~/volumes/app/postgres/:/var/lib/postgresql/data:rw
    networks:
      - backend-network

  # Importante: ao rodar o pgadmin, será necessário registrar a conexão no IP como: host.docker.internal e não localhost
  pg-db-admin:
    image: "dpage/pgadmin4:4.22"
    environment:
      PGADMIN_DEFAULT_EMAIL: "renatoalexandrejusto@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - backend-network
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge
